---
abstract: 'Fetch a tree of bugzilla bugs blocking a bug'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Bugzilla-BugTree
requires:
  Getopt::Long: 0
  LWP::UserAgent: 0
  Moo: 0
  Pod::Usage: 0
  Term::ANSIColor: 0
  Term::Clui: 0
  URI: 0
  XML::Simple: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/www-bugzilla-bugtree/issues
  homepage: http://perl.wdlabs.com/WWW-Bugzilla-BugTree/
  repository: git://github.com/plicease/www-bugzilla-bugtree.git
version: 0.03
